#!/bin/bash
mount=$(lsblk -lp|grep "part $" | awk '{print $1, "(" $4 ")"}')
[[ "$mount" = "" ]] && exit 1
chosen=$( echo $mount | dmenu -i -p "Pick a drive to mount" | awk '{printf($1)}')
[[ "$chosen" = "" ]] && exit 1
dirs=$(find /mnt /media /home -mindepth 1  -maxdepth 2 -type d)
mountpoint=$(echo "$dirs" | dmenu -i -p "pick folder")
[[ "$mountpoint" = "" ]] && exit 1
if [[ ! -d "$mountpoint" ]]; then
    mdir=$( echo -e "yes\nno"| dmenu -i -p "do you wanna make the folder")
    [[ "$mdir" = "yes" ]] &&  mkdir -p "$mountpoint" || exit 1
fi
mount $chosen $mountpoint && pgrep -x dunst && notify-send "$chosen mounted $mountpoint"

