#!/bin/bash
mount=$( lsblk -lp|grep 'home\|mnt\|media' | awk '{print $1, "(" $4 ")"}')
[[ "$mount" = "" ]] && exit 1
chosen=$( echo $mount | dmenu -i -p "Pick a drive to dismount" | awk '{printf($1)}')
[[ "$chosen" = "" ]] && exit 1
sudo umount "$chosen" 2>/dev/null  && exit 0

